services:
  postgres:
    container_name: postgres-sql-payflow
    image: postgres
    environment:
      POSTGRES_USER: payflow
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: db_payflow
    volumes:
      - postgres:/data/postgres
    ports:
      - 5434:5432
    networks:
      - spring-demo
    restart: unless-stopped

networks:
  spring-demo:
    driver: bridge

volumes:
  postgres:
    driver: local